apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicea
  name: servicea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - image: hzhyvinskyi/bch-servicea:0.0.1
        name: servicea
